### ISSUE TITLE
New Intel:  [forsaken]

### ISSUE THREAD

**Issue by TorresNahu** [Miss-placed/DECLASSIFIED#276]
### Name

The Magnificent Two

### Faction

Omega

### Season

Season 6

### Type of intel

Audio Log

### Description

The audio log is resting by the wall on the ground to the left of the broken teleporter in the fuel processing area.

### Map

forsaken

### Location Coordinates

[249.29362837413686, 244.5]

**Comment by bola2010** [comment]
Thank u for helping us! This intel has already been added in our latest release and will soon be added to master.

Latest release: https://github.com/Miss-placed/DECLASSIFIED/releases
