### ISSUE TITLE
New Misc Marker:  [firebaseZ_spawn]

### ISSUE THREAD

**Issue by NamelesZombie** [Miss-placed/DECLASSIFIED#397]
### Name

OMEGA RADIO

### Type of Misc Marker

Omega Radio

### Description

On top of a table, across from the bunk beds in the upper floor of the aromory. Have to turn on power first

### Map

firebaseZ_spawn

### Location Coordinates

[300.9558734823382, 330.3515634503805]

**Comment by sol3uk** [comment]
Thanks for the input @NamelesZombie, this has been added!
