### ISSUE TITLE
Intel Fix: B-14 Wiretap Transcript [forsaken][RS6Do2]

### ISSUE THREAD

**Issue by cliftonm1996** [Miss-placed/DECLASSIFIED#401]
### Name

B-14 Wiretap Transcript

### Intel Id

RS6Do2

### Fix Needed

location is outbreak, not forsaken

**Comment by sol3uk** [comment]
https://github.com/Miss-placed/DECLASSIFIED/commit/940dfabe9174a1c27dd7280004ea632a3534695f

**Comment by sol3uk** [comment]
@cliftonm1996 thanks for the contribution, your edits have been applied!
Thanks for using the app 😄
