### ISSUE TITLE
Intel Fix: Echelon Breach Report [echelon][OOnDo24]

### ISSUE THREAD

**Issue by SxyDragon** [Miss-placed/DECLASSIFIED#403]
### Name

Requiem/Omega

### Fix Needed

There seems to be a requiem intel that is labeled as an omega intel.

The website says that theres 200 requiem intel and 161 omega intel, however it should be 201 requiem and 160 omega intel.

Don't know which one exactly but if i find while on my intel hunt i will update this for whatever one it is

**Comment by sol3uk** [comment]
@SxyDragon thanks for this, looks like it's one of the omega documents. Will investigate.
