### ISSUE TITLE
Intel Fix: Transformed Apple Crate [golova][RS3Ar4]

### ISSUE THREAD

**Issue by SxyDragon** [Miss-placed/DECLASSIFIED#404]
### Name

Transformed Apple Crate

### Intel Id

RS3Ar4

### Fix Needed

Picture for reference

**Comment by SxyDragon** [comment]
ive got a screenshot but cant submit it without it turning into text through github

**Comment by sol3uk** [comment]
@SxyDragon you can upload to us via the discord 
https://discord.com/invite/4Xqj8XntFe
or via [imgur](https://imgur.com/), we will then upload it to the specific imgur album and push a fix
