### ISSUE TITLE
New Misc Marker:  [mauerDerToten_streets]

### ISSUE THREAD

**Issue by Axteddy** [Miss-placed/DECLASSIFIED#409]
### Name

Omega Radio

### Type of Misc Marker

Omega Radio

### Description

Inside the green tent, to the right on the table

### Map

mauerDerToten_streets

### Location Coordinates

[377.81057107427455, 326.69606430827434]

**Comment by sol3uk** [comment]
Thanks for this, not sure if the location you've provided is correct? 
I could be wrong, but from memory the green tent is here on the map?
I can get the location if I redownload the game and check, but would you be able to upload a screenshot or double check to make sure this is right?
![image](https://user-images.githubusercontent.com/26093813/216795349-12f6b714-3c4c-4083-91d4-b607c8df14ad.png)

Thanks!

**Comment by sol3uk** [comment]
@Axteddy
