### ISSUE TITLE
Bug - Map is changed back to previous after clicking contribute

### ISSUE THREAD

**Issue by sol3uk** [Miss-placed/DECLASSIFIED#419]
After clicking any of the contribution buttons it will seemingly redirect you to your previously saved map, but only when navigating to a different map, then clicking contribute.

**Comment by sol3uk** [comment]
Seems to be liberty falls specific.

**Comment by Odinnh** [comment]
could it be because we set the default map to liberty falls, but we might need to set it in multiple areas

**Comment by sol3uk** [comment]
Any form of interaction with the settings menu will cause this behaviour

**Comment by sol3uk** [comment]
I found the issue, we weren't updating the state of the URL id which was causing stale state to update the map when it was re rendered
