### ISSUE TITLE
Intel Fix: Secret Contact [outbreak][DS4Ra1]

### ISSUE THREAD

**Issue by adoseofdatatoxin** [Miss-placed/DECLASSIFIED#421]
### Game

Cold War

### Name

Secret Contact

### Intel Id

DS4Ra1

### Fix Needed

none of the outbreak radios show when the current map only filter is applied

**Comment by sol3uk** [comment]
Yes the outbreak repeatable radio Intel has no specific map it can be taken from and can technically be achieved on any of the maps. I'll add an exception in the filtering to allow for items with no location. Possibly get a seperate filter in for them too.

**Comment by sol3uk** [comment]
I've added a fix for this for now. I will add an item to my project backlog to address this with a filter for "show non map specific collectibles"

**Comment by sol3uk** [comment]
Yes that will be taken into account 👍
