### ISSUE TITLE
Intel Fix: Order Of Operations [duga][OS6Do2]

### ISSUE THREAD

**Issue by qmzi** [Miss-placed/DECLASSIFIED#423]
### Game

Cold War

### Name

Order Of Operations

### Intel Id

OS6Do2

### Fix Needed

I don't see it in any Outbreak documents through all seasons and factions, it says it's from Season 6 Omega documents. What if it's from forsaken?

**Comment by sol3uk** [comment]
According to our original data and our intel hunters, this was found by killing special and elite enemies in Duga. If this is not the case, if you can provide a source, then we can update this to where it's correctly found. Reading the intel however, it would make sense that it would appear on an outbreak map, as this speaks specifically about events in the outbreak easter eggs.
