### ISSUE TITLE
challenge tracker bug ?

### ISSUE THREAD

**Issue by mrthompson0102** [Miss-placed/DECLASSIFIED#428]
everytime you open the challenge tracker it goes back a version to where Liberty Falls won't show,Then you gotta close out the app again & restart it to get it to show (V3?)I do get all of my challenge progress back though.

**Comment by sol3uk** [comment]
Yes this is the legacy version of the app, it should open in a new tab, but apologies for the confusion. We've got some changes in the development branch coming tonight that clear this up by removing the link to the challenge tracker and legacy app and moving it to the settings menu for now. The challenge tracker is also being reworked in the future.

**Comment by sol3uk** [comment]
Actually ill leave this open till we push tonight.
