### ISSUE TITLE
Feature Request: Weapon Specific Wall Buys

### ISSUE THREAD

**Issue by browntown-13** [Miss-placed/DECLASSIFIED#438]
### Description

It would be really nice to see which weapon each wall buy is selling, as they never change. Thanks!

**Comment by sol3uk** [comment]
Thanks Yeah we already do this. The wall buys should display the names of the weapons as their title. If you spot any that haven't been updated, please let us know which ones are missing that info!

**Comment by browntown-13** [comment]
Forgot to check Terminus, my bad. The ones on Terminus do, but none of the ones on Liberty Falls do.

**Comment by sol3uk** [comment]
Ah yes, I believe I did this yesterday on the development branch. I'll get it published as soon as I can

**Comment by sol3uk** [comment]
@browntown-13 this has been released now. Thanks for raising. If you spot any ones I may have missed please let me know and I'll sort it!
