### ISSUE TITLE
Add more words for google to pick up

### ISSUE THREAD

**Issue by arekm** [Miss-placed/DECLASSIFIED#45]
When initially looking for such map I failed to do so. google doesn't pick up this page or map itself it anyone is looking for outbreak intel map or a specific region intel map.

Would be nice if more description would be added to indicate this is outbreak, names of round maps intel map etc.

Can't help with SEO though.

**Comment by Odinnh** [comment]
we're working on a second version of the map, we would be more seo optimised once we've released v2

**Comment by sol3uk** [comment]
We can use these from google as a starting point. We should include the most basic of descriptions and stuff so people can see us properly on google.
However, I'm not sure that we should spend that much time working on this however, might be better to just get the tool in the hands of some of the zombies youtubers discord channels so people are aware and we will just get organic traffic which will drive us up the rankings regardless.
https://developers.google.com/search/docs/advanced/crawling/special-tags
https://developers.google.com/search/docs/advanced/guidelines/webmaster-guidelines

**Comment by sol3uk** [comment]
I've added the app to the google search console 
https://search.google.com/search-console?utm_source=about-page&resource_id=https://declassified.netlify.app/
